http://127.0.0.1:8000/Health

###

POST http://127.0.0.1:8000/dev/createClientwithAnimal
Content-Type: application/json

{
  "Full_Name": "Aramis Martinez",
  "Email": "martinezcruzaj@gmail.com",
  "Phone": 9394395156,
  "Password": "Arathenoob2454!"
}

###